/* tslint:disable */
/* eslint-disable */

export class WasmWorldgenDiagnostic {
    free(): void;
    [Symbol.dispose](): void;
    field_hash_hex(): string;
    generator_version(): number;
    height(): number;
    maximum(): number;
    mean(): number;
    minimum(): number;
    constructor(seed: string, width: number, height: number);
    sample_count(): bigint;
    stage_id(): string;
    stage_seed_hex(): string;
    stage_version(): number;
    values(): Uint16Array;
    width(): number;
}

export class WasmWorldgenGeology {
    free(): void;
    [Symbol.dispose](): void;
    basin_potential(): Float32Array;
    boundary_edge_count(): number;
    boundary_kinds(): Uint8Array;
    boundary_plate_ids(): Uint16Array;
    boundary_samples(): Uint32Array;
    buoyancy_index(): Float32Array;
    continental_area_fraction(): number;
    continental_collision_edges(): number;
    continental_rift_edges(): number;
    crust_age_myr(): Float32Array;
    crust_density_kg_per_m3(): Float32Array;
    crust_kind(): Uint8Array;
    crust_province_id(): Uint16Array;
    crust_thickness_km(): Float32Array;
    crustal_strain(): Float32Array;
    faces(): Uint32Array;
    generator_version(): number;
    geological_boundary_regimes(): Uint8Array;
    geology_hash_hex(): string;
    history_seed_hex(): string;
    level(): number;
    mean_continental_age_myr(): number;
    mean_continental_thickness_km(): number;
    mean_oceanic_age_myr(): number;
    mean_oceanic_thickness_km(): number;
    neighbor_offsets(): Uint32Array;
    neighbors(): Uint32Array;
    constructor(seed: string, level: number, plate_count: number);
    ocean_continent_subduction_edges(): number;
    oceanic_area_fraction(): number;
    oceanic_ridge_edges(): number;
    oceanic_subduction_edges(): number;
    orogenic_history(): Float32Array;
    plate_continental_fractions(): Float64Array;
    plate_count(): number;
    plate_ids(): Uint16Array;
    plate_mean_crust_age_myr(): Float64Array;
    plate_mean_crust_thickness_km(): Float64Array;
    plate_oceanic_fractions(): Float64Array;
    plate_scale_classes(): Uint8Array;
    plate_transitional_fractions(): Float64Array;
    positions(): Float64Array;
    property_seed_hex(): string;
    province_seed_hex(): string;
    ridge_history(): Float32Array;
    rift_history(): Float32Array;
    sample_count(): number;
    stage_id(): string;
    stage_seed_hex(): string;
    stage_version(): number;
    subduction_history(): Float32Array;
    subduction_polarities(): Uint8Array;
    subsidence_history(): Float32Array;
    tectonic_hash_hex(): string;
    topology_hash_hex(): string;
    transform_edges(): number;
    transform_history(): Float32Array;
    transitional_area_fraction(): number;
    transitional_divergence_edges(): number;
    trench_history(): Float32Array;
    volcanic_arc_history(): Float32Array;
}

export class WasmWorldgenInheritance {
    free(): void;
    [Symbol.dispose](): void;
    added_sample_count(): number;
    basin_potential(): Float32Array;
    boundary_coarse_source_indices(): Uint32Array;
    boundary_hash_hex(): string;
    boundary_kinds(): Uint8Array;
    boundary_normal_rates_m_per_year(): Float64Array;
    boundary_samples(): Uint32Array;
    boundary_shear_rates_m_per_year(): Float64Array;
    buoyancy_index(): Float32Array;
    coarse_level(): number;
    coarse_sample_count(): number;
    coarse_topology_hash_hex(): string;
    compensated_buoyancy_index(): Float32Array;
    crust_age_myr(): Float32Array;
    crust_density_kg_per_m3(): Float32Array;
    crust_kind(): Uint8Array;
    crust_province_id(): Uint16Array;
    crust_thickness_km(): Float32Array;
    crustal_strain(): Float32Array;
    effective_elastic_thickness_km(): Float32Array;
    equivalent_global_water_depth_m(): number;
    faces(): Uint32Array;
    fine_boundary_edge_count(): number;
    fine_level(): number;
    fine_sample_count(): number;
    fine_topology_hash_hex(): string;
    fragment_ids(): Uint16Array;
    fragmentation_propensity(): Float32Array;
    generator_version(): number;
    geological_boundary_regimes(): Uint8Array;
    geology_hash_hex(): string;
    inheritance_hash_hex(): string;
    inherited_sample_mask(): Uint8Array;
    internal_heat_flux_w_per_m2(): number;
    isostatic_mantle_density_kg_per_m3(): number;
    kinematic_domain_ids(): Uint16Array;
    lithosphere_hash_hex(): string;
    mantle_dynamic_support_index(): Float32Array;
    mantle_thermal_expansivity_per_k(): number;
    mantle_upwelling_index(): Float32Array;
    nearest_coarse_source(): Uint32Array;
    neighbor_offsets(): Uint32Array;
    neighbors(): Uint32Array;
    constructor(seed: string, coarse_level: number, fine_level: number, plate_count: number);
    ocean_water_density_kg_per_m3(): number;
    orogenic_history(): Float32Array;
    parameter_hash_hex(): string;
    plate_count(): number;
    plate_ids(): Uint16Array;
    positions(): Float64Array;
    provenance_hash_hex(): string;
    radius_m(): number;
    ridge_history(): Float32Array;
    rift_history(): Float32Array;
    stage_id(): string;
    stage_version(): number;
    strength_index(): Float32Array;
    structural_fabric_strength(): Float32Array;
    structural_zone_kind(): Uint8Array;
    subduction_history(): Float32Array;
    subduction_polarities(): Uint8Array;
    subsidence_history(): Float32Array;
    surface_gravity_m_s2(): number;
    surface_water_mass_kg(): number;
    tectonic_hash_hex(): string;
    thermal_anomaly_index(): Float32Array;
    transform_history(): Float32Array;
    trench_history(): Float32Array;
    volcanic_arc_history(): Float32Array;
    weakness_index(): Float32Array;
}

export class WasmWorldgenLithosphere {
    free(): void;
    [Symbol.dispose](): void;
    boundary_edge_count(): number;
    boundary_kinds(): Uint8Array;
    boundary_samples(): Uint32Array;
    compensated_buoyancy_index(): Float32Array;
    continental_margin_sample_count(): number;
    crust_kind(): Uint8Array;
    crustal_strain(): Float32Array;
    effective_elastic_thickness_km(): Float32Array;
    faces(): Uint32Array;
    fragment_angular_velocities_rad_per_myr(): Float64Array;
    fragment_area_fractions_of_parent(): Float64Array;
    fragment_area_steradians(): Float64Array;
    fragment_ids(): Uint16Array;
    fragment_kinds(): Uint8Array;
    fragment_mean_propensity(): Float64Array;
    fragment_mean_weakness(): Float64Array;
    fragment_parent_plate_ids(): Uint16Array;
    fragment_seed_samples(): Uint32Array;
    fragmentation_propensity(): Float32Array;
    fragmented_area_fraction(): number;
    generator_version(): number;
    geological_boundary_regimes(): Uint8Array;
    geology_hash_hex(): string;
    kinematic_domain_ids(): Uint16Array;
    level(): number;
    lithosphere_hash_hex(): string;
    mantle_dynamic_support_index(): Float32Array;
    mantle_seed_hex(): string;
    mantle_upwelling_index(): Float32Array;
    mean_dynamic_support_index(): number;
    mean_effective_elastic_thickness_km(): number;
    mean_mantle_upwelling_index(): number;
    mean_strength_index(): number;
    mean_weakness_index(): number;
    mechanical_seed_hex(): string;
    microplate_count(): number;
    neighbor_offsets(): Uint32Array;
    neighbors(): Uint32Array;
    constructor(seed: string, level: number, plate_count: number);
    orogenic_history(): Float32Array;
    plate_count(): number;
    plate_ids(): Uint16Array;
    positions(): Float64Array;
    refinement_seed_hex(): string;
    ridge_history(): Float32Array;
    rift_history(): Float32Array;
    rift_zone_sample_count(): number;
    sample_count(): number;
    stage_id(): string;
    stage_seed_hex(): string;
    stage_version(): number;
    strength_index(): Float32Array;
    structural_fabric_strength(): Float32Array;
    structural_zone_kind(): Uint8Array;
    subduction_history(): Float32Array;
    suture_sample_count(): number;
    tectonic_fragment_count(): number;
    tectonic_hash_hex(): string;
    terrane_count(): number;
    thermal_anomaly_index(): Float32Array;
    topology_hash_hex(): string;
    transform_history(): Float32Array;
    transform_zone_sample_count(): number;
    weakness_index(): Float32Array;
}

export class WasmWorldgenTectonics {
    free(): void;
    [Symbol.dispose](): void;
    boundary_edge_count(): number;
    boundary_kinds(): Uint8Array;
    boundary_normal_rates_m_per_year(): Float64Array;
    boundary_plate_ids(): Uint16Array;
    boundary_samples(): Uint32Array;
    boundary_shear_rates_m_per_year(): Float64Array;
    convergent_edge_count(): number;
    divergent_edge_count(): number;
    faces(): Uint32Array;
    generator_version(): number;
    level(): number;
    maximum_plate_area_fraction(): number;
    mean_plate_area_fraction(): number;
    mean_reference_speed_mm_per_year(): number;
    minimum_plate_area_fraction(): number;
    minimum_seed_separation_rad(): number;
    neighbor_offsets(): Uint32Array;
    neighbors(): Uint32Array;
    constructor(seed: string, level: number, plate_count: number);
    plate_angular_velocities_rad_per_myr(): Float64Array;
    plate_area_steradians(): Float64Array;
    plate_count(): number;
    plate_euler_poles(): Float64Array;
    plate_ids(): Uint16Array;
    plate_seed_samples(): Uint32Array;
    positions(): Float64Array;
    sample_count(): number;
    stage_id(): string;
    stage_seed_hex(): string;
    stage_version(): number;
    tectonic_hash_hex(): string;
    topology_hash_hex(): string;
    transform_edge_count(): number;
}

export class WasmWorldgenTopology {
    free(): void;
    [Symbol.dispose](): void;
    area_coefficient_of_variation(): number;
    area_steradians(): Float64Array;
    birth_levels(): Uint8Array;
    edge_coefficient_of_variation(): number;
    edge_count(): number;
    face_count(): number;
    faces(): Uint32Array;
    five_neighbor_count(): number;
    generator_version(): number;
    interface_coefficient_of_variation(): number;
    level(): number;
    maximum_area_steradians(): number;
    maximum_edge_arc_radians(): number;
    maximum_interface_arc_radians(): number;
    mean_area_steradians(): number;
    mean_edge_arc_radians(): number;
    mean_interface_arc_radians(): number;
    minimum_area_steradians(): number;
    minimum_edge_arc_radians(): number;
    minimum_interface_arc_radians(): number;
    neighbor_arc_lengths_rad(): Float64Array;
    neighbor_interface_arc_lengths_rad(): Float64Array;
    neighbor_offsets(): Uint32Array;
    neighbors(): Uint32Array;
    constructor(level: number);
    parent_edges(): Uint32Array;
    positions(): Float64Array;
    sample_count(): number;
    six_neighbor_count(): number;
    topology_hash_hex(): string;
    total_area_steradians(): number;
}

export function worldgen_engine_version(): number;

export function worldgen_protocol_version(): number;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
    readonly __wbg_wasmworldgendiagnostic_free: (a: number, b: number) => void;
    readonly __wbg_wasmworldgengeology_free: (a: number, b: number) => void;
    readonly __wbg_wasmworldgeninheritance_free: (a: number, b: number) => void;
    readonly __wbg_wasmworldgenlithosphere_free: (a: number, b: number) => void;
    readonly __wbg_wasmworldgentectonics_free: (a: number, b: number) => void;
    readonly __wbg_wasmworldgentopology_free: (a: number, b: number) => void;
    readonly wasmworldgendiagnostic_field_hash_hex: (a: number) => [number, number];
    readonly wasmworldgendiagnostic_generator_version: (a: number) => number;
    readonly wasmworldgendiagnostic_height: (a: number) => number;
    readonly wasmworldgendiagnostic_maximum: (a: number) => number;
    readonly wasmworldgendiagnostic_mean: (a: number) => number;
    readonly wasmworldgendiagnostic_minimum: (a: number) => number;
    readonly wasmworldgendiagnostic_new: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly wasmworldgendiagnostic_sample_count: (a: number) => bigint;
    readonly wasmworldgendiagnostic_stage_id: (a: number) => [number, number];
    readonly wasmworldgendiagnostic_stage_seed_hex: (a: number) => [number, number];
    readonly wasmworldgendiagnostic_stage_version: (a: number) => number;
    readonly wasmworldgendiagnostic_values: (a: number) => [number, number];
    readonly wasmworldgendiagnostic_width: (a: number) => number;
    readonly wasmworldgengeology_basin_potential: (a: number) => [number, number];
    readonly wasmworldgengeology_boundary_edge_count: (a: number) => number;
    readonly wasmworldgengeology_boundary_kinds: (a: number) => [number, number];
    readonly wasmworldgengeology_boundary_plate_ids: (a: number) => [number, number];
    readonly wasmworldgengeology_boundary_samples: (a: number) => [number, number];
    readonly wasmworldgengeology_buoyancy_index: (a: number) => [number, number];
    readonly wasmworldgengeology_continental_area_fraction: (a: number) => number;
    readonly wasmworldgengeology_continental_collision_edges: (a: number) => number;
    readonly wasmworldgengeology_continental_rift_edges: (a: number) => number;
    readonly wasmworldgengeology_crust_age_myr: (a: number) => [number, number];
    readonly wasmworldgengeology_crust_density_kg_per_m3: (a: number) => [number, number];
    readonly wasmworldgengeology_crust_kind: (a: number) => [number, number];
    readonly wasmworldgengeology_crust_province_id: (a: number) => [number, number];
    readonly wasmworldgengeology_crust_thickness_km: (a: number) => [number, number];
    readonly wasmworldgengeology_crustal_strain: (a: number) => [number, number];
    readonly wasmworldgengeology_faces: (a: number) => [number, number];
    readonly wasmworldgengeology_generator_version: (a: number) => number;
    readonly wasmworldgengeology_geological_boundary_regimes: (a: number) => [number, number];
    readonly wasmworldgengeology_geology_hash_hex: (a: number) => [number, number];
    readonly wasmworldgengeology_history_seed_hex: (a: number) => [number, number];
    readonly wasmworldgengeology_level: (a: number) => number;
    readonly wasmworldgengeology_mean_continental_age_myr: (a: number) => number;
    readonly wasmworldgengeology_mean_continental_thickness_km: (a: number) => number;
    readonly wasmworldgengeology_mean_oceanic_age_myr: (a: number) => number;
    readonly wasmworldgengeology_mean_oceanic_thickness_km: (a: number) => number;
    readonly wasmworldgengeology_neighbor_offsets: (a: number) => [number, number];
    readonly wasmworldgengeology_neighbors: (a: number) => [number, number];
    readonly wasmworldgengeology_new: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly wasmworldgengeology_ocean_continent_subduction_edges: (a: number) => number;
    readonly wasmworldgengeology_oceanic_area_fraction: (a: number) => number;
    readonly wasmworldgengeology_oceanic_ridge_edges: (a: number) => number;
    readonly wasmworldgengeology_oceanic_subduction_edges: (a: number) => number;
    readonly wasmworldgengeology_orogenic_history: (a: number) => [number, number];
    readonly wasmworldgengeology_plate_continental_fractions: (a: number) => [number, number];
    readonly wasmworldgengeology_plate_count: (a: number) => number;
    readonly wasmworldgengeology_plate_ids: (a: number) => [number, number];
    readonly wasmworldgengeology_plate_mean_crust_age_myr: (a: number) => [number, number];
    readonly wasmworldgengeology_plate_mean_crust_thickness_km: (a: number) => [number, number];
    readonly wasmworldgengeology_plate_oceanic_fractions: (a: number) => [number, number];
    readonly wasmworldgengeology_plate_scale_classes: (a: number) => [number, number];
    readonly wasmworldgengeology_plate_transitional_fractions: (a: number) => [number, number];
    readonly wasmworldgengeology_positions: (a: number) => [number, number];
    readonly wasmworldgengeology_property_seed_hex: (a: number) => [number, number];
    readonly wasmworldgengeology_province_seed_hex: (a: number) => [number, number];
    readonly wasmworldgengeology_ridge_history: (a: number) => [number, number];
    readonly wasmworldgengeology_rift_history: (a: number) => [number, number];
    readonly wasmworldgengeology_sample_count: (a: number) => number;
    readonly wasmworldgengeology_stage_id: (a: number) => [number, number];
    readonly wasmworldgengeology_stage_seed_hex: (a: number) => [number, number];
    readonly wasmworldgengeology_stage_version: (a: number) => number;
    readonly wasmworldgengeology_subduction_history: (a: number) => [number, number];
    readonly wasmworldgengeology_subduction_polarities: (a: number) => [number, number];
    readonly wasmworldgengeology_subsidence_history: (a: number) => [number, number];
    readonly wasmworldgengeology_tectonic_hash_hex: (a: number) => [number, number];
    readonly wasmworldgengeology_topology_hash_hex: (a: number) => [number, number];
    readonly wasmworldgengeology_transform_edges: (a: number) => number;
    readonly wasmworldgengeology_transform_history: (a: number) => [number, number];
    readonly wasmworldgengeology_transitional_area_fraction: (a: number) => number;
    readonly wasmworldgengeology_transitional_divergence_edges: (a: number) => number;
    readonly wasmworldgengeology_trench_history: (a: number) => [number, number];
    readonly wasmworldgengeology_volcanic_arc_history: (a: number) => [number, number];
    readonly wasmworldgeninheritance_added_sample_count: (a: number) => number;
    readonly wasmworldgeninheritance_basin_potential: (a: number) => [number, number];
    readonly wasmworldgeninheritance_boundary_coarse_source_indices: (a: number) => [number, number];
    readonly wasmworldgeninheritance_boundary_hash_hex: (a: number) => [number, number];
    readonly wasmworldgeninheritance_boundary_kinds: (a: number) => [number, number];
    readonly wasmworldgeninheritance_boundary_normal_rates_m_per_year: (a: number) => [number, number];
    readonly wasmworldgeninheritance_boundary_samples: (a: number) => [number, number];
    readonly wasmworldgeninheritance_boundary_shear_rates_m_per_year: (a: number) => [number, number];
    readonly wasmworldgeninheritance_buoyancy_index: (a: number) => [number, number];
    readonly wasmworldgeninheritance_coarse_level: (a: number) => number;
    readonly wasmworldgeninheritance_coarse_sample_count: (a: number) => number;
    readonly wasmworldgeninheritance_coarse_topology_hash_hex: (a: number) => [number, number];
    readonly wasmworldgeninheritance_compensated_buoyancy_index: (a: number) => [number, number];
    readonly wasmworldgeninheritance_crust_age_myr: (a: number) => [number, number];
    readonly wasmworldgeninheritance_crust_density_kg_per_m3: (a: number) => [number, number];
    readonly wasmworldgeninheritance_crust_kind: (a: number) => [number, number];
    readonly wasmworldgeninheritance_crust_province_id: (a: number) => [number, number];
    readonly wasmworldgeninheritance_crust_thickness_km: (a: number) => [number, number];
    readonly wasmworldgeninheritance_crustal_strain: (a: number) => [number, number];
    readonly wasmworldgeninheritance_effective_elastic_thickness_km: (a: number) => [number, number];
    readonly wasmworldgeninheritance_equivalent_global_water_depth_m: (a: number) => number;
    readonly wasmworldgeninheritance_faces: (a: number) => [number, number];
    readonly wasmworldgeninheritance_fine_boundary_edge_count: (a: number) => number;
    readonly wasmworldgeninheritance_fine_level: (a: number) => number;
    readonly wasmworldgeninheritance_fine_topology_hash_hex: (a: number) => [number, number];
    readonly wasmworldgeninheritance_fragment_ids: (a: number) => [number, number];
    readonly wasmworldgeninheritance_fragmentation_propensity: (a: number) => [number, number];
    readonly wasmworldgeninheritance_geological_boundary_regimes: (a: number) => [number, number];
    readonly wasmworldgeninheritance_geology_hash_hex: (a: number) => [number, number];
    readonly wasmworldgeninheritance_inheritance_hash_hex: (a: number) => [number, number];
    readonly wasmworldgeninheritance_inherited_sample_mask: (a: number) => [number, number];
    readonly wasmworldgeninheritance_internal_heat_flux_w_per_m2: (a: number) => number;
    readonly wasmworldgeninheritance_isostatic_mantle_density_kg_per_m3: (a: number) => number;
    readonly wasmworldgeninheritance_kinematic_domain_ids: (a: number) => [number, number];
    readonly wasmworldgeninheritance_lithosphere_hash_hex: (a: number) => [number, number];
    readonly wasmworldgeninheritance_mantle_dynamic_support_index: (a: number) => [number, number];
    readonly wasmworldgeninheritance_mantle_thermal_expansivity_per_k: (a: number) => number;
    readonly wasmworldgeninheritance_mantle_upwelling_index: (a: number) => [number, number];
    readonly wasmworldgeninheritance_nearest_coarse_source: (a: number) => [number, number];
    readonly wasmworldgeninheritance_neighbor_offsets: (a: number) => [number, number];
    readonly wasmworldgeninheritance_neighbors: (a: number) => [number, number];
    readonly wasmworldgeninheritance_new: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
    readonly wasmworldgeninheritance_ocean_water_density_kg_per_m3: (a: number) => number;
    readonly wasmworldgeninheritance_orogenic_history: (a: number) => [number, number];
    readonly wasmworldgeninheritance_parameter_hash_hex: (a: number) => [number, number];
    readonly wasmworldgeninheritance_plate_count: (a: number) => number;
    readonly wasmworldgeninheritance_plate_ids: (a: number) => [number, number];
    readonly wasmworldgeninheritance_positions: (a: number) => [number, number];
    readonly wasmworldgeninheritance_provenance_hash_hex: (a: number) => [number, number];
    readonly wasmworldgeninheritance_radius_m: (a: number) => number;
    readonly wasmworldgeninheritance_ridge_history: (a: number) => [number, number];
    readonly wasmworldgeninheritance_rift_history: (a: number) => [number, number];
    readonly wasmworldgeninheritance_stage_id: (a: number) => [number, number];
    readonly wasmworldgeninheritance_stage_version: (a: number) => number;
    readonly wasmworldgeninheritance_strength_index: (a: number) => [number, number];
    readonly wasmworldgeninheritance_structural_fabric_strength: (a: number) => [number, number];
    readonly wasmworldgeninheritance_structural_zone_kind: (a: number) => [number, number];
    readonly wasmworldgeninheritance_subduction_history: (a: number) => [number, number];
    readonly wasmworldgeninheritance_subduction_polarities: (a: number) => [number, number];
    readonly wasmworldgeninheritance_subsidence_history: (a: number) => [number, number];
    readonly wasmworldgeninheritance_surface_gravity_m_s2: (a: number) => number;
    readonly wasmworldgeninheritance_surface_water_mass_kg: (a: number) => number;
    readonly wasmworldgeninheritance_tectonic_hash_hex: (a: number) => [number, number];
    readonly wasmworldgeninheritance_thermal_anomaly_index: (a: number) => [number, number];
    readonly wasmworldgeninheritance_transform_history: (a: number) => [number, number];
    readonly wasmworldgeninheritance_trench_history: (a: number) => [number, number];
    readonly wasmworldgeninheritance_volcanic_arc_history: (a: number) => [number, number];
    readonly wasmworldgeninheritance_weakness_index: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_boundary_kinds: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_boundary_samples: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_compensated_buoyancy_index: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_continental_margin_sample_count: (a: number) => number;
    readonly wasmworldgenlithosphere_crust_kind: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_crustal_strain: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_effective_elastic_thickness_km: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_faces: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragment_angular_velocities_rad_per_myr: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragment_area_fractions_of_parent: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragment_area_steradians: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragment_ids: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragment_kinds: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragment_mean_propensity: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragment_mean_weakness: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragment_parent_plate_ids: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragment_seed_samples: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragmentation_propensity: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_fragmented_area_fraction: (a: number) => number;
    readonly wasmworldgenlithosphere_geological_boundary_regimes: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_geology_hash_hex: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_kinematic_domain_ids: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_lithosphere_hash_hex: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_mantle_dynamic_support_index: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_mantle_seed_hex: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_mantle_upwelling_index: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_mean_dynamic_support_index: (a: number) => number;
    readonly wasmworldgenlithosphere_mechanical_seed_hex: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_microplate_count: (a: number) => number;
    readonly wasmworldgenlithosphere_neighbor_offsets: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_neighbors: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_new: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly wasmworldgenlithosphere_orogenic_history: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_plate_ids: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_positions: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_refinement_seed_hex: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_ridge_history: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_rift_history: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_stage_id: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_stage_seed_hex: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_stage_version: (a: number) => number;
    readonly wasmworldgenlithosphere_strength_index: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_structural_fabric_strength: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_structural_zone_kind: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_subduction_history: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_tectonic_fragment_count: (a: number) => number;
    readonly wasmworldgenlithosphere_tectonic_hash_hex: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_terrane_count: (a: number) => number;
    readonly wasmworldgenlithosphere_thermal_anomaly_index: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_topology_hash_hex: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_transform_history: (a: number) => [number, number];
    readonly wasmworldgenlithosphere_weakness_index: (a: number) => [number, number];
    readonly wasmworldgentectonics_boundary_kinds: (a: number) => [number, number];
    readonly wasmworldgentectonics_boundary_normal_rates_m_per_year: (a: number) => [number, number];
    readonly wasmworldgentectonics_boundary_plate_ids: (a: number) => [number, number];
    readonly wasmworldgentectonics_boundary_samples: (a: number) => [number, number];
    readonly wasmworldgentectonics_boundary_shear_rates_m_per_year: (a: number) => [number, number];
    readonly wasmworldgentectonics_divergent_edge_count: (a: number) => number;
    readonly wasmworldgentectonics_faces: (a: number) => [number, number];
    readonly wasmworldgentectonics_maximum_plate_area_fraction: (a: number) => number;
    readonly wasmworldgentectonics_mean_plate_area_fraction: (a: number) => number;
    readonly wasmworldgentectonics_mean_reference_speed_mm_per_year: (a: number) => number;
    readonly wasmworldgentectonics_minimum_plate_area_fraction: (a: number) => number;
    readonly wasmworldgentectonics_minimum_seed_separation_rad: (a: number) => number;
    readonly wasmworldgentectonics_neighbor_offsets: (a: number) => [number, number];
    readonly wasmworldgentectonics_neighbors: (a: number) => [number, number];
    readonly wasmworldgentectonics_new: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly wasmworldgentectonics_plate_angular_velocities_rad_per_myr: (a: number) => [number, number];
    readonly wasmworldgentectonics_plate_area_steradians: (a: number) => [number, number];
    readonly wasmworldgentectonics_plate_euler_poles: (a: number) => [number, number];
    readonly wasmworldgentectonics_plate_ids: (a: number) => [number, number];
    readonly wasmworldgentectonics_plate_seed_samples: (a: number) => [number, number];
    readonly wasmworldgentectonics_positions: (a: number) => [number, number];
    readonly wasmworldgentectonics_stage_id: (a: number) => [number, number];
    readonly wasmworldgentectonics_stage_seed_hex: (a: number) => [number, number];
    readonly wasmworldgentectonics_stage_version: (a: number) => number;
    readonly wasmworldgentectonics_tectonic_hash_hex: (a: number) => [number, number];
    readonly wasmworldgentectonics_topology_hash_hex: (a: number) => [number, number];
    readonly wasmworldgentectonics_transform_edge_count: (a: number) => number;
    readonly wasmworldgentopology_area_coefficient_of_variation: (a: number) => number;
    readonly wasmworldgentopology_area_steradians: (a: number) => [number, number];
    readonly wasmworldgentopology_birth_levels: (a: number) => [number, number];
    readonly wasmworldgentopology_edge_coefficient_of_variation: (a: number) => number;
    readonly wasmworldgentopology_edge_count: (a: number) => number;
    readonly wasmworldgentopology_face_count: (a: number) => number;
    readonly wasmworldgentopology_faces: (a: number) => [number, number];
    readonly wasmworldgentopology_five_neighbor_count: (a: number) => number;
    readonly wasmworldgentopology_interface_coefficient_of_variation: (a: number) => number;
    readonly wasmworldgentopology_maximum_area_steradians: (a: number) => number;
    readonly wasmworldgentopology_maximum_edge_arc_radians: (a: number) => number;
    readonly wasmworldgentopology_maximum_interface_arc_radians: (a: number) => number;
    readonly wasmworldgentopology_mean_area_steradians: (a: number) => number;
    readonly wasmworldgentopology_mean_edge_arc_radians: (a: number) => number;
    readonly wasmworldgentopology_mean_interface_arc_radians: (a: number) => number;
    readonly wasmworldgentopology_minimum_area_steradians: (a: number) => number;
    readonly wasmworldgentopology_minimum_edge_arc_radians: (a: number) => number;
    readonly wasmworldgentopology_minimum_interface_arc_radians: (a: number) => number;
    readonly wasmworldgentopology_neighbor_arc_lengths_rad: (a: number) => [number, number];
    readonly wasmworldgentopology_neighbor_interface_arc_lengths_rad: (a: number) => [number, number];
    readonly wasmworldgentopology_neighbor_offsets: (a: number) => [number, number];
    readonly wasmworldgentopology_neighbors: (a: number) => [number, number];
    readonly wasmworldgentopology_new: (a: number) => [number, number, number];
    readonly wasmworldgentopology_parent_edges: (a: number) => [number, number];
    readonly wasmworldgentopology_positions: (a: number) => [number, number];
    readonly wasmworldgentopology_sample_count: (a: number) => number;
    readonly wasmworldgentopology_six_neighbor_count: (a: number) => number;
    readonly wasmworldgentopology_topology_hash_hex: (a: number) => [number, number];
    readonly wasmworldgentopology_total_area_steradians: (a: number) => number;
    readonly worldgen_engine_version: () => number;
    readonly wasmworldgeninheritance_fine_sample_count: (a: number) => number;
    readonly wasmworldgenlithosphere_boundary_edge_count: (a: number) => number;
    readonly wasmworldgenlithosphere_mean_effective_elastic_thickness_km: (a: number) => number;
    readonly wasmworldgenlithosphere_mean_mantle_upwelling_index: (a: number) => number;
    readonly wasmworldgenlithosphere_mean_strength_index: (a: number) => number;
    readonly wasmworldgenlithosphere_mean_weakness_index: (a: number) => number;
    readonly wasmworldgenlithosphere_rift_zone_sample_count: (a: number) => number;
    readonly wasmworldgenlithosphere_sample_count: (a: number) => number;
    readonly wasmworldgenlithosphere_suture_sample_count: (a: number) => number;
    readonly wasmworldgenlithosphere_transform_zone_sample_count: (a: number) => number;
    readonly wasmworldgentectonics_boundary_edge_count: (a: number) => number;
    readonly wasmworldgentectonics_convergent_edge_count: (a: number) => number;
    readonly wasmworldgentectonics_sample_count: (a: number) => number;
    readonly wasmworldgeninheritance_generator_version: (a: number) => number;
    readonly wasmworldgenlithosphere_generator_version: (a: number) => number;
    readonly wasmworldgentectonics_generator_version: (a: number) => number;
    readonly wasmworldgentopology_generator_version: (a: number) => number;
    readonly worldgen_protocol_version: () => number;
    readonly wasmworldgenlithosphere_level: (a: number) => number;
    readonly wasmworldgenlithosphere_plate_count: (a: number) => number;
    readonly wasmworldgentectonics_level: (a: number) => number;
    readonly wasmworldgentectonics_plate_count: (a: number) => number;
    readonly wasmworldgentopology_level: (a: number) => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __wbindgen_free: (a: number, b: number, c: number) => void;
    readonly __wbindgen_malloc: (a: number, b: number) => number;
    readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
    readonly __externref_table_dealloc: (a: number) => void;
    readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
