export default [
  { "id": "basalt", "name": "Basalt", "distribution": "both", "occurrenceFamily": "rock-mass", "tags": ["volcanic", "igneous", "rock"] },
  { "id": "granite", "name": "Granite", "distribution": "both", "occurrenceFamily": "rock-mass", "tags": ["igneous", "rock", "felsic"] },
  { "id": "sandstone", "name": "Sandstone", "distribution": "both", "occurrenceFamily": "rock-mass", "tags": ["sedimentary", "rock"] },
  { "id": "limestone", "name": "Limestone", "distribution": "both", "occurrenceFamily": "rock-mass", "tags": ["sedimentary", "rock", "carbonate"] },
  { "id": "shale", "name": "Shale", "distribution": "both", "occurrenceFamily": "rock-mass", "tags": ["sedimentary", "rock"] },
  { "id": "clay", "name": "Clay", "distribution": "both", "occurrenceFamily": "sediment", "tags": ["sedimentary", "mineral"] },
  { "id": "sand", "name": "Sand", "distribution": "both", "occurrenceFamily": "sediment", "tags": ["sedimentary", "loose"] },
  { "id": "regolith", "name": "Regolith", "distribution": "both", "occurrenceFamily": "sediment", "tags": ["loose", "surface"] },
  { "id": "water-ice", "name": "Water Ice", "distribution": "both", "occurrenceFamily": "ice-body", "tags": ["icy", "volatile"] },
  { "id": "saline-water", "name": "Saline Water", "distribution": "both", "occurrenceFamily": "aqueous-fluid", "tags": ["wet", "liquid"] },
  { "id": "fresh-water", "name": "Fresh Water", "distribution": "both", "occurrenceFamily": "aqueous-fluid", "tags": ["wet", "liquid"] },
  { "id": "atmospheric-gas", "name": "Atmospheric Gas", "distribution": "regional", "occurrenceFamily": "atmosphere", "tags": ["gas", "atmosphere"] },
  { "id": "wood", "name": "Wood", "distribution": "regional", "occurrenceFamily": "vegetation", "tags": ["biological", "organic"] },
  { "id": "plant-biomass", "name": "Plant Biomass", "distribution": "regional", "occurrenceFamily": "vegetation", "tags": ["biological", "organic"] },
  { "id": "peat", "name": "Peat", "distribution": "regional", "occurrenceFamily": "organic-soil", "tags": ["biological", "organic", "sedimentary"] },
  { "id": "organic-soil", "name": "Organic Soil", "distribution": "regional", "occurrenceFamily": "organic-soil", "tags": ["biological", "organic"] },
  { "id": "carbon-rich-rock", "name": "Carbon-Rich Rock", "distribution": "both", "occurrenceFamily": "rock-mass", "tags": ["carbonRich", "rock"] },
  { "id": "permafrost", "name": "Permafrost", "distribution": "both", "occurrenceFamily": "ice-body", "tags": ["icy", "loose"] },

  { "id": "iron-ore", "name": "Iron Ore", "distribution": "localized", "occurrenceFamily": "ore-body", "tags": ["volcanic", "metallic", "ore"] },
  { "id": "copper-ore", "name": "Copper Ore", "distribution": "localized", "occurrenceFamily": "ore-body", "tags": ["volcanic", "metallic", "ore"] },
  { "id": "aluminum-ore", "name": "Aluminum Ore", "distribution": "localized", "occurrenceFamily": "ore-body", "tags": ["felsic", "metallic", "ore"] },
  { "id": "zinc-ore", "name": "Zinc Ore", "distribution": "localized", "occurrenceFamily": "ore-body", "tags": ["volcanic", "metallic", "ore"] },
  { "id": "nickel-ore", "name": "Nickel Ore", "distribution": "localized", "occurrenceFamily": "ore-body", "tags": ["volcanic", "metallic", "ore"] },
  { "id": "titanium-ore", "name": "Titanium Ore", "distribution": "localized", "occurrenceFamily": "ore-body", "tags": ["igneous", "metallic", "ore"] },
  { "id": "manganese-ore", "name": "Manganese Ore", "distribution": "localized", "occurrenceFamily": "ore-body", "tags": ["metallic", "ore", "sedimentary"] },
  { "id": "sulfur", "name": "Sulfur", "distribution": "localized", "occurrenceFamily": "mineral-body", "tags": ["volcanic", "mineral"] },
  { "id": "halite", "name": "Halite", "distribution": "localized", "occurrenceFamily": "evaporite", "tags": ["evaporite", "mineral"] },
  { "id": "phosphate-rock", "name": "Phosphate Rock", "distribution": "localized", "occurrenceFamily": "mineral-body", "tags": ["sedimentary", "mineral"] },
  { "id": "quartz", "name": "Quartz", "distribution": "localized", "occurrenceFamily": "mineral-body", "tags": ["igneous", "mineral", "felsic"] },
  { "id": "graphite", "name": "Graphite", "distribution": "localized", "occurrenceFamily": "mineral-body", "tags": ["carbonRich", "mineral"] },
  { "id": "coal", "name": "Coal", "distribution": "localized", "occurrenceFamily": "sediment", "tags": ["biological", "sedimentary", "carbonRich"] },
  { "id": "brine", "name": "Brine", "distribution": "localized", "occurrenceFamily": "aqueous-fluid", "tags": ["wet", "liquid", "saline"] },
  { "id": "groundwater", "name": "Groundwater", "distribution": "localized", "occurrenceFamily": "aqueous-fluid", "tags": ["wet", "liquid"] },
  { "id": "natural-gas", "name": "Natural Gas", "distribution": "localized", "occurrenceFamily": "reservoir-gas", "tags": ["carbonRich", "gas", "hydrocarbon"] },
  { "id": "hydrocarbons", "name": "Hydrocarbons", "distribution": "localized", "occurrenceFamily": "hydrocarbon-liquid", "tags": ["carbonRich", "hydrocarbon"] },
  { "id": "gas-clathrate", "name": "Gas Clathrate", "distribution": "localized", "occurrenceFamily": "ice-body", "tags": ["icy", "volatile", "gas"] },
  { "id": "ammonia-water-solution", "name": "Ammonia-Water Solution", "distribution": "localized", "occurrenceFamily": "aqueous-fluid", "tags": ["volatile", "liquid"] },
  { "id": "magma", "name": "Magma", "distribution": "localized", "occurrenceFamily": "magma", "tags": ["volcanic", "liquid"] },
  { "id": "geothermal-fluid", "name": "Geothermal Fluid", "distribution": "localized", "occurrenceFamily": "hydrothermal-fluid", "tags": ["volcanic", "wet", "liquid"] },
  { "id": "lithium-brine", "name": "Lithium Brine", "distribution": "localized", "occurrenceFamily": "aqueous-fluid", "tags": ["wet", "saline", "metallic"] },
  { "id": "rare-earth-ore", "name": "Rare Earth Ore", "distribution": "localized", "occurrenceFamily": "ore-body", "tags": ["metallic", "ore", "igneous"] },

  { "id": "mixed-sediment", "name": "Mixed Sediment", "distribution": "both", "occurrenceFamily": "sediment", "tags": ["sedimentary", "loose"] },
  { "id": "carbonate-rock", "name": "Carbonate Rock", "distribution": "both", "occurrenceFamily": "rock-mass", "tags": ["sedimentary", "rock", "carbonate"] },
  { "id": "gypsum", "name": "Gypsum", "distribution": "both", "occurrenceFamily": "evaporite", "tags": ["evaporite", "mineral"] },
  { "id": "obsidian", "name": "Obsidian", "distribution": "both", "occurrenceFamily": "rock-mass", "tags": ["volcanic", "igneous", "rock"] },
  { "id": "pumice", "name": "Pumice", "distribution": "both", "occurrenceFamily": "rock-mass", "tags": ["volcanic", "igneous", "rock"] }
];
