const range = (min, max) => Object.freeze([min, max]);

export const RESOURCE_COMPOSITION_TEMPLATES = Object.freeze({
  basalt: Object.freeze({ plagioclase: range(45, 60), augite: range(20, 35), olivine: range(5, 20) }),
  granite: Object.freeze({ quartz: range(20, 35), orthoclase: range(25, 40), plagioclase: range(20, 35), biotite: range(5, 15) }),
  sandstone: Object.freeze({ quartz: range(70, 90), calcite: range(5, 20), plagioclase: range(2, 10) }),
  limestone: Object.freeze({ calcite: range(75, 95), dolomite: range(5, 20), quartz: range(1, 8) }),
  shale: Object.freeze({ illite: range(35, 55), kaolinite: range(15, 30), quartz: range(20, 40), pyrite: range(1, 5) }),
  clay: Object.freeze({ kaolinite: range(45, 70), illite: range(20, 45), quartz: range(5, 15) }),
  sand: Object.freeze({ quartz: range(80, 98), plagioclase: range(2, 15) }),
  regolith: Object.freeze({ quartz: range(30, 50), plagioclase: range(20, 40), kaolinite: range(10, 25), hematite: range(2, 10) }),
  'water-ice': Object.freeze({ waterIce: 100 }),
  wood: Object.freeze({ cellulose: range(55, 70), lignin: range(30, 45) }),
  'plant-biomass': Object.freeze({ cellulose: range(60, 75), lignin: range(25, 40) }),
  peat: Object.freeze({ cellulose: range(45, 60), lignin: range(40, 55) }),
  'organic-soil': Object.freeze({ quartz: range(30, 45), kaolinite: range(20, 35), cellulose: range(15, 25), lignin: range(10, 20) }),
  'carbon-rich-rock': Object.freeze({ graphite: range(35, 60), quartz: range(40, 65) }),
  permafrost: Object.freeze({ waterIce: range(45, 65), quartz: range(20, 35), kaolinite: range(10, 20) }),
  'iron-ore': Object.freeze({ hematite: range(20, 70), magnetite: range(5, 30), goethite: range(2, 15), quartz: range(5, 25) }),
  'copper-ore': Object.freeze({ chalcopyrite: range(30, 60), bornite: range(5, 20), pyrite: range(5, 15), quartz: range(10, 30) }),
  'aluminum-ore': Object.freeze({ gibbsite: range(30, 60), boehmite: range(10, 30), kaolinite: range(5, 20), hematite: range(5, 15) }),
  'zinc-ore': Object.freeze({ sphalerite: range(40, 70), galena: range(5, 20), pyrite: range(5, 15), quartz: range(5, 20) }),
  'nickel-ore': Object.freeze({ pentlandite: range(30, 60), pyrrhotite: range(10, 30), chalcopyrite: range(5, 15), quartz: range(10, 25) }),
  'titanium-ore': Object.freeze({ ilmenite: range(45, 75), rutile: range(10, 30), quartz: range(10, 25) }),
  'manganese-ore': Object.freeze({ pyrolusite: range(45, 75), rhodochrosite: range(10, 30), quartz: range(10, 25) }),
  sulfur: Object.freeze({ sulfur: 100 }),
  halite: Object.freeze({ halite: 100 }),
  'phosphate-rock': Object.freeze({ fluorapatite: range(60, 80), calcite: range(10, 25), quartz: range(5, 15) }),
  quartz: Object.freeze({ quartz: 100 }),
  graphite: Object.freeze({ graphite: 100 }),
  coal: Object.freeze({ graphite: range(65, 85), kaolinite: range(10, 25), pyrite: range(2, 10) }),
  'gas-clathrate': Object.freeze({ methaneHydrate: 100 }),
  'rare-earth-ore': Object.freeze({ monazite: range(30, 55), bastnasite: range(15, 35), xenotime: range(5, 20), quartz: range(10, 25) }),
  'mixed-sediment': Object.freeze({ quartz: range(45, 65), plagioclase: range(15, 30), kaolinite: range(10, 20), calcite: range(5, 15) }),
  'carbonate-rock': Object.freeze({ calcite: range(60, 80), dolomite: range(20, 40) }),
  gypsum: Object.freeze({ gypsum: 100 }),
  obsidian: Object.freeze({ silicaGlass: 100 }),
  pumice: Object.freeze({ silicaGlass: range(75, 90), plagioclase: range(10, 25) }),
  brine: Object.freeze({ H2O: range(80, 95), NaCl: range(3, 15), MgCl2: range(1, 5), KCl: range(1, 3), CaSO4: range(1, 2) }),
  'natural-gas': Object.freeze({ CH4: range(60, 95), C2H6: range(1, 15), CO2: range(1, 10), N2: range(1, 8) }),
});
