export const RESOURCE_COMPOSITION_NOTES = Object.freeze({
  basalt: 'Plagioclase + pyroxene ± olivine',
  granite: 'Quartz + feldspar + mica',
  sandstone: 'Quartz grains with carbonate/feldspar cement',
  limestone: 'Calcite-dominant carbonate rock',
  shale: 'Fine clay minerals, silica, and minor sulfide',
  clay: 'Kaolinite / illite mix',
  sand: 'Quartz-dominated granular material',
  regolith: 'Weathered silicate minerals and iron oxide',
  'water-ice': 'H2O ice',
  'saline-water': 'NaCl-dominated saline water',
  'fresh-water': 'Low-mineral liquid water',
  'atmospheric-gas': 'Ambient atmospheric mixture',
  wood: 'Cellulose and lignin-rich plant material',
  'plant-biomass': 'Cellulose and lignin-rich plant material',
  peat: 'Partially decomposed lignocellulosic material',
  'organic-soil': 'Mineral soil with lignocellulosic organic matter',
  'carbon-rich-rock': 'Graphitic siliceous rock',
  permafrost: 'Ice-cemented silicate soil',
  'mixed-sediment': 'Quartz, feldspar, clay, and carbonate sediment',
  'carbonate-rock': 'Calcite / dolomite matrix',
  gypsum: 'CaSO4·2H2O evaporite',
  obsidian: 'Silica-rich volcanic glass',
  pumice: 'Silica-rich vesicular volcanic glass',
});

export const RESOURCE_DESCRIPTORS = Object.freeze({
  'iron-ore': Object.freeze(['Hematite-rich', 'Magnetite-rich', 'Goethite-bearing', 'Mixed oxide']),
  'copper-ore': Object.freeze(['Chalcopyrite-rich', 'Bornite-bearing', 'Pyrite-bearing', 'Porphyry-type']),
  'aluminum-ore': Object.freeze(['Gibbsite-dominant', 'Boehmite-rich', 'Lateritic bauxite']),
  'zinc-ore': Object.freeze(['Sphalerite-rich', 'Galena-bearing', 'Carbonate-hosted']),
  'nickel-ore': Object.freeze(['Pentlandite-bearing', 'Pyrrhotite-rich', 'Sulfide-rich']),
  'titanium-ore': Object.freeze(['Ilmenite-dominant', 'Rutile-bearing', 'Mixed titanium oxide']),
  'manganese-ore': Object.freeze(['Pyrolusite-rich', 'Rhodochrosite-bearing', 'Mixed manganese mineralization']),
  sulfur: Object.freeze(['Native sulfur', 'Volcanic sublimate', 'Hydrothermal']),
  halite: Object.freeze(['Bedded evaporite', 'Domal', 'Caprock']),
  'phosphate-rock': Object.freeze(['Fluorapatite-rich', 'Carbonate-bearing', 'Nodular']),
  quartz: Object.freeze(['Vein quartz', 'Quartzite', 'Chert nodules']),
  graphite: Object.freeze(['Flake graphite', 'Amorphous', 'Vein graphite']),
  coal: Object.freeze(['Anthracite', 'Bituminous', 'Sub-bituminous', 'Lignite']),
  brine: Object.freeze(['NaCl-dominated', 'Mg-rich', 'K-rich', 'Mixed evaporite']),
  groundwater: Object.freeze(['Confined aquifer', 'Unconfined aquifer', 'Karst system']),
  'natural-gas': Object.freeze(['Dry methane', 'Wet gas', 'CO2-rich', 'N2-bearing']),
  hydrocarbons: Object.freeze(['Light fraction', 'Heavy crude', 'Bitumen-like', 'Mixed']),
  'gas-clathrate': Object.freeze(['Methane clathrate', 'Mixed-gas clathrate', 'CO2 clathrate']),
  'ammonia-water-solution': Object.freeze(['Dilute ammonia', 'Concentrated ammonia-water']),
  magma: Object.freeze(['Basaltic', 'Andesitic', 'Rhyolitic', 'Ultramafic']),
  'geothermal-fluid': Object.freeze(['High-enthalpy steam', 'Mixed steam-water', 'Superheated brine']),
  'lithium-brine': Object.freeze(['Li-Cl dominant', 'Li-B-rich', 'Evaporite-hosted']),
  'rare-earth-ore': Object.freeze(['Monazite-rich', 'Bastnasite-rich', 'Xenotime-bearing', 'Mixed rare-earth mineralization']),
});
