export const FEATURE_TYPES = Object.freeze([
  'Mineral Deposit',
  'Geological Formation',
  'Aquifer',
  'Gas Reservoir',
  'Cave / Cavern',
  'Ravine',
  'Fault',
  'Crater',
  'Volcanic Vent',
  'Hydrothermal System',
  'Magma Chamber',
  'Ice Body',
  'Salt Basin',
  'Outcrop',
]);

export const FEATURE_FALLBACK_RESOURCE = Object.freeze({
  'Mineral Deposit': 'iron-ore',
  'Geological Formation': 'carbonate-rock',
  'Aquifer': 'groundwater',
  'Gas Reservoir': 'natural-gas',
  'Cave / Cavern': 'carbonate-rock',
  'Ravine': 'mixed-sediment',
  'Fault': 'quartz',
  'Crater': 'mixed-sediment',
  'Volcanic Vent': 'sulfur',
  'Hydrothermal System': 'geothermal-fluid',
  'Magma Chamber': 'magma',
  'Ice Body': 'water-ice',
  'Salt Basin': 'halite',
  'Outcrop': 'carbonate-rock',
});
