import { OCCURRENCE_FAMILIES } from '../resources/occurrenceFamilies.js';

export const FEATURE_ALLOWED_FAMILIES = Object.freeze({
  'Mineral Deposit': new Set([OCCURRENCE_FAMILIES.ORE_BODY, OCCURRENCE_FAMILIES.MINERAL_BODY]),
  'Geological Formation': new Set([OCCURRENCE_FAMILIES.ROCK_MASS, OCCURRENCE_FAMILIES.SEDIMENT, OCCURRENCE_FAMILIES.MINERAL_BODY, OCCURRENCE_FAMILIES.HYDROCARBON_LIQUID]),
  'Aquifer': new Set([OCCURRENCE_FAMILIES.AQUEOUS_FLUID]),
  'Gas Reservoir': new Set([OCCURRENCE_FAMILIES.RESERVOIR_GAS]),
  'Cave / Cavern': new Set([OCCURRENCE_FAMILIES.ROCK_MASS, OCCURRENCE_FAMILIES.SEDIMENT, OCCURRENCE_FAMILIES.MINERAL_BODY]),
  'Ravine': new Set([OCCURRENCE_FAMILIES.ROCK_MASS, OCCURRENCE_FAMILIES.SEDIMENT]),
  'Fault': new Set([OCCURRENCE_FAMILIES.ROCK_MASS, OCCURRENCE_FAMILIES.ORE_BODY, OCCURRENCE_FAMILIES.MINERAL_BODY]),
  'Crater': new Set([OCCURRENCE_FAMILIES.ROCK_MASS, OCCURRENCE_FAMILIES.SEDIMENT, OCCURRENCE_FAMILIES.ORE_BODY]),
  'Volcanic Vent': new Set([OCCURRENCE_FAMILIES.MINERAL_BODY, OCCURRENCE_FAMILIES.ROCK_MASS]),
  'Hydrothermal System': new Set([OCCURRENCE_FAMILIES.AQUEOUS_FLUID, OCCURRENCE_FAMILIES.HYDROTHERMAL_FLUID, OCCURRENCE_FAMILIES.ORE_BODY, OCCURRENCE_FAMILIES.MINERAL_BODY]),
  'Magma Chamber': new Set([OCCURRENCE_FAMILIES.MAGMA]),
  'Ice Body': new Set([OCCURRENCE_FAMILIES.ICE_BODY]),
  'Salt Basin': new Set([OCCURRENCE_FAMILIES.EVAPORITE, OCCURRENCE_FAMILIES.AQUEOUS_FLUID]),
  'Outcrop': new Set([OCCURRENCE_FAMILIES.ROCK_MASS, OCCURRENCE_FAMILIES.ORE_BODY, OCCURRENCE_FAMILIES.MINERAL_BODY]),
});

export function allowedPhysicalStates(featureType) {
  switch (featureType) {
    case 'Aquifer': return ['Liquid', 'Mixed'];
    case 'Gas Reservoir': return ['Gaseous', 'Mixed'];
    case 'Magma Chamber': return ['Liquid'];
    case 'Ice Body': return ['Solid'];
    case 'Hydrothermal System': return ['Liquid', 'Mixed'];
    default: return null;
  }
}
